[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'lib/openzeppelin-contracts/contracts=lib/forge-std/openzeppelin-contracts/contracts'
]

[lint]
exclude_lints = ["asm-keccak256"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
